<?php 

$field_group_array = array(
	'key' => 'group_6383bf2c9011f',
	'title' => 'Timetable',
	'fields' => array(
		array(
			'key' => 'field_6383c2106f3aa',
			'label' => 'Items',
			'name' => 'items',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'pagination' => 0,
			'min' => 1,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Item',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6383c21a6f3ab',
					'label' => 'Name',
					'name' => 'name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6383c2106f3aa',
				),
				array(
					'key' => 'field_6383c2226f3ac',
					'label' => 'Description',
					'name' => 'description',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6383c2106f3aa',
				),
				array(
					'key' => 'field_6383c22b6f3ad',
					'label' => 'Duration',
					'name' => 'duration',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6383c2106f3aa',
				),
			),
		),
	),
	'location' => array(
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'is_k17_acf_block' => 1,
	'is_k17_acf_component' => 0,
	'modified' => 1669581326,
);

