<?php

$field_group_array = array(
	'key' => 'group_64105dffdabee',
	'title' => 'Popup Block',
	'fields' => array(
		array(
			'key' => 'field_64105e0076da2',
			'label' => 'ID',
			'name' => 'id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Identifier is used to trigger the popup',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64105e7276dae',
			'label' => 'Title',
			'name' => 'title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Title will be shown in Popup Header',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64105e2276da3',
			'label' => 'Popup Builder',
			'name' => 'popup_builder',
			'aria-label' => '',
			'type' => 'k17_block_builder',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_64105e2b816bb3.39239556' => array(
					'key' => 'layout_64105e2b816bb3.39239556',
					'name' => '1_column_row',
					'label' => '1 Col Row',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
					'block_group_key' => 'group_62f4166d11d40',
				),
				'layout_64105e3176da4' => array(
					'key' => 'layout_64105e3176da4',
					'name' => '2_column_row',
					'label' => '2 Col Row',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
					'block_group_key' => 'group_62f41dc2f12fe',
				),
				'layout_64105e3476da5' => array(
					'key' => 'layout_64105e3476da5',
					'name' => '3_column_row',
					'label' => '3 Col Row',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
					'block_group_key' => 'group_62f41c17c7053',
				),
				'layout_64105e3876da6' => array(
					'key' => 'layout_64105e3876da6',
					'name' => 'downloads',
					'label' => 'Downloads',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6383cc4b168ef',
							'label' => 'Items',
							'name' => 'items',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'row',
							'pagination' => 0,
							'min' => 1,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_6383cc64168f0',
									'label' => 'File',
									'name' => 'file',
									'aria-label' => '',
									'type' => 'file',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_size' => '',
									'max_size' => '',
									'mime_types' => '',
									'parent_repeater' => 'field_6383cc4b168ef',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
					'block_group_key' => 'group_6383cc4a1bd19',
				),
				'layout_64105e3c76da7' => array(
					'key' => 'layout_64105e3c76da7',
					'name' => '2_column_row_text_video',
					'label' => '2 Col Row Text Video',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
					'block_group_key' => 'group_64020930955ab',
				),
				'layout_64105e4576da8' => array(
					'key' => 'layout_64105e4576da8',
					'name' => '2_column_row_text_k17_video',
					'label' => '2 Col Row Text Klick17 Video',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
					'block_group_key' => 'group_64020930955ac',
				),
				'layout_64105e4876da9' => array(
					'key' => 'layout_64105e4876da9',
					'name' => 'oembed',
					'label' => 'oEmbed',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_63a1bbf467738',
							'label' => 'embed',
							'name' => 'embed',
							'aria-label' => '',
							'type' => 'oembed',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'width' => '',
							'height' => '',
						),
					),
					'min' => '',
					'max' => '',
					'block_group_key' => 'group_63a1bbf2a4661',
				),
				'layout_64105e4f76daa' => array(
					'key' => 'layout_64105e4f76daa',
					'name' => 'klick17_video',
					'label' => 'Klick17 Video',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6407a3579ddb1',
							'label' => 'Video',
							'name' => 'video',
							'aria-label' => '',
							'type' => 'k7vp-video-player',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
					),
					'min' => '',
					'max' => '',
					'block_group_key' => 'group_6407a3573c2be',
				),
				'layout_64105e5376dab' => array(
					'key' => 'layout_64105e5376dab',
					'name' => 'testimonial_slide',
					'label' => 'Testimonial Slide',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_640387c395d88',
							'label' => 'Testimonies',
							'name' => 'testimonies',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'pagination' => 0,
							'min' => 1,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_640387ea95d89',
									'label' => 'Testimony',
									'name' => 'testimony',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'rows' => '',
									'placeholder' => '',
									'new_lines' => '',
									'parent_repeater' => 'field_640387c395d88',
								),
								array(
									'key' => 'field_640387f495d8a',
									'label' => 'Author',
									'name' => 'author',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_640387c395d88',
								),
								array(
									'key' => 'field_6404d7f82829d',
									'label' => 'Position',
									'name' => 'position',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_640387c395d88',
								),
								array(
									'key' => 'field_640387fe95d8b',
									'label' => 'Image',
									'name' => 'image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'url',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_640387c395d88',
								),
							),
						),
						array(
							'key' => 'field_640cdf1270f28',
							'label' => 'Slides To Show',
							'name' => 'slides_to_show',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => 'How many testimonies will be shown in one slide?',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => 2,
							'min' => 1,
							'max' => 4,
							'placeholder' => '',
							'step' => 1,
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_640cdf5f70f29',
							'label' => 'Slides To Scroll',
							'name' => 'slides_to_scroll',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => 'How many testimonies will be shown when slide?',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => 1,
							'min' => 1,
							'max' => 4,
							'placeholder' => '',
							'step' => 1,
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_640cdf8e70f2a',
							'label' => 'Center Padding',
							'name' => 'center_padding',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => 'Center padding between two testimonials',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => 60,
							'min' => 0,
							'max' => '',
							'placeholder' => '',
							'step' => 1,
							'prepend' => '',
							'append' => 'px',
						),
						array(
							'key' => 'field_640cdfc370f2b',
							'label' => 'Dots',
							'name' => 'dots',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_640cdfda70f2c',
							'label' => 'Arrows',
							'name' => 'arrows',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_640cdffc70f2d',
							'label' => 'Infinite',
							'name' => 'infinite',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
					'block_group_key' => 'group_640387a5b011b',
				),
				'layout_64105e6176dac' => array(
					'key' => 'layout_64105e6176dac',
					'name' => 'image_text_cards_slider',
					'label' => 'Image Text Cards Slider',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_640cec2738ed9',
							'label' => 'Title',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_640ce98a9b56d',
							'label' => 'Cards',
							'name' => 'cards',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'pagination' => 0,
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Card',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_640ce9a99b56e',
									'label' => 'Image',
									'name' => 'image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_640ce98a9b56d',
								),
								array(
									'key' => 'field_640ce9b59b56f',
									'label' => 'Text',
									'name' => 'text',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_640ce98a9b56d',
								),
								array(
									'key' => 'field_640cea8fe27d1',
									'label' => 'Card Option',
									'name' => '',
									'aria-label' => '',
									'type' => 'accordion',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'open' => 0,
									'multi_expand' => 0,
									'endpoint' => 0,
									'parent_repeater' => 'field_640ce98a9b56d',
								),
								array(
									'key' => 'field_640cea9ee27d2',
									'label' => 'Image Resolution',
									'name' => 'image_resolution',
									'aria-label' => '',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'thumbnail' => 'Thumbnail',
										'medium' => 'Medium',
										'large' => 'Large',
										'full' => 'Full',
									),
									'default_value' => 'medium',
									'return_format' => 'value',
									'multiple' => 0,
									'allow_null' => 0,
									'ui' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'parent_repeater' => 'field_640ce98a9b56d',
								),
							),
						),
						array(
							'key' => 'field_640cdf1270f28',
							'label' => 'Slides To Show',
							'name' => 'slides_to_show',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => 'How many testimonies will be shown in one slide?',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => 2,
							'min' => 1,
							'max' => 4,
							'placeholder' => '',
							'step' => 1,
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_640cdf5f70f29',
							'label' => 'Slides To Scroll',
							'name' => 'slides_to_scroll',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => 'How many testimonies will be shown when slide?',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => 1,
							'min' => 1,
							'max' => 4,
							'placeholder' => '',
							'step' => 1,
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_640cdf8e70f2a',
							'label' => 'Center Padding',
							'name' => 'center_padding',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => 'Center padding between two testimonials',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => 60,
							'min' => 0,
							'max' => '',
							'placeholder' => '',
							'step' => 1,
							'prepend' => '',
							'append' => 'px',
						),
						array(
							'key' => 'field_640cdfc370f2b',
							'label' => 'Dots',
							'name' => 'dots',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_640cdfda70f2c',
							'label' => 'Arrows',
							'name' => 'arrows',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_640cdffc70f2d',
							'label' => 'Infinite',
							'name' => 'infinite',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
					'block_group_key' => 'group_640ce98a41a27',
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => '+ Add Block',
		),
		array(
			'key' => 'field_64105e8776daf',
			'label' => 'Popup Settings',
			'name' => '',
			'aria-label' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_64105e9376db0',
			'label' => 'Footer Text',
			'name' => 'footer_text',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64105e9c76db1',
			'label' => 'CTA',
			'name' => 'cta',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_64105ea376db2',
					'label' => 'Text',
					'name' => 'text',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_64105eb076db3',
					'label' => 'URL',
					'name' => 'url',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'is_k17_acf_block' => 1,
	'is_k17_acf_component' => 0,
	'modified' => 1678794470,
);
